### PR TITLE
Technical content for openc2 command and associated agents, targets, variables

### PR DESCRIPTION
**Pull request by dlemire60**
This PR defines:

- an `openc2` CACAO command object
- agents to support MQTT and HTTPS transfer of OpenC2 messages
- targets to associate OpenC2 Actuator Profiles with the addressees of OpenC2 messages
- standard variables to pass parameters to the agents
- associated supporting content & references

### CODE REVIEW

**Review by davaya — APPROVED** [review]
The table in Section 3.1 says "The common workflow step_variables property for an openc2 command MUST include an agent for message transfer." but the example shows the "agent" property and the step_variables property with topics as described in Section 4.

Suggest including both "agent" and "step_variables" in the table Property Names

**Review by davaya — APPROVED** [review]
(first review didn't take)

**Comment by dlemire60** [comment]
> Suggest including both "agent" and "step_variables" in the table Property Names

Those aren't in the table for the `openc2` action object because they're defined at a higher level in the CACAO spec. 

`agent_definitions` is a playbook property (section 3.1).  `step_variables` is a workflow step common property (section 4.1).  It would make sense to add explicit references to make the connection but probably not to repeat the definition in our extension spec.  I've tried to align examples in the extension spec with those in the CACAO spec, but sometimes there are ambiguities. I can probably leverage the CACAO Roaster to help with example creation but I'm not fully confident it's completely compliant w/ the v2.0 spec (although that's certainly their stated goal).

**Comment by dlemire60** [comment]
Approved for merging on the 26 June working call.

**Pull request merged**
